### ISSUE TITLE
加载的动画并没有

### ISSUE THREAD

**Issue by xiaomsh** [Someonewow/SubmitButton#2]
无法显示正在加载的动画

**Comment by Someonewow** [comment]
@wenchaosong 能否进一步描述下你遇到的bug，plz~

**Comment by xiaomsh** [comment]
就是说 clone 你的项目,运行,看不到加载的动画,转圈的动画看不到,drawLoading 方法运行了  但是看不到

**Comment by Someonewow** [comment]
@wenchaosong 问题已找到，是由于硬件加速不能完全支持所有的渲染操作，因此在某些机型上面就会出现你所说的问题，晚些时间我会fix这个bug并关闭issue，非常感谢你提的issue~
